name: CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          rm -rf .venv
          uv venv
          ls -l
          source .venv/Scripts/active 
          uv pip install --upgrade pip
          uv pip install -e . --dev

      - name: run tests
        run: ./test.sh

      - name: formating check for code
        run: autopep8 --recursive --diff --exit-code .

      - name: run linter
        run: flake8 /src

      - name: security checks
        run: safety check --full-report

      - name: detect secrets
        run: detect-secrets scan --update .secrets.baseline

      - name: audit secrets
        run: detect-secrets audit .secrets.baseline

      - name: run SAST
        run: bandit -r . -l

      - name: run audit
        run: pip-audit
