name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev --no-root

      - name: formating check for code
        run: poetry run autopep8 --in-place --recursive --aggressive --aggressive src

      - name: run linter
        run: poetry run flake8 src

      - name: security checks
        run: poetry run safety check --full-report

      - name: detect secrets
        run: poetry run detect-secrets scan .secrets.baseline

      - name: audit secrets
        continue-on-error: true
        run: poetry run detect-secrets audit .secrets.baseline

      - name: run SAST
        run: poetry run bandit -r src -l

      - name: run pylint
        continue-on-error: true
        run: poetry run pylint src --output-format=text

      - name: deadcode detector vulture
        run: poetry run vulture src --min-confidence 80 --sort-by-size

      - name: run Radon complexity analyser
        run: poetry run radon cc src -a -nc

      #- name: run pytest and coverage
      #  run: poetry run pytest --cov=src --cov-report=xml --cov-fail-under=5

      - name: run pyright for typechecks
        run: poetry run pyright
